In [50]:
import numpy as np
import seaborn as sns
import pandas as pd

In [51]:
df = pd.read_csv("D:\\Dashboard\\miDirectarios\\ML\\start tech python\\ML Algorithms\\Logistic Regression\\Classification preprocessed data Python.csv", header=0)

In [52]:
# in sklearn our independant variablsem must be two dimensional so we use two brackets
x = df.drop(columns=['Sold'])


In [53]:
y=df['Sold']

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

In [55]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [56]:
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(404, 16) (404,) (102, 16) (102,)


In [57]:
from sklearn import preprocessing

In [58]:
scaler = preprocessing.StandardScaler().fit(x_train)

In [59]:
x_train_scaled = scaler.transform(x_train)

In [60]:
scaler = preprocessing.StandardScaler().fit(x_test)
x_test_scaled = scaler.transform(x_test)

In [61]:
from sklearn.neighbors import KNeighborsClassifier

# KNN with single neighbor onlyt

In [62]:
#  KNN with only one neighbor
knn_classification1 = KNeighborsClassifier(n_neighbors=1)

In [63]:
knn_classification1.fit(x_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=1)

In [64]:
confusion_matrix(y_test, knn_classification1.predict(x_test_scaled))

array([[30, 28],
       [19, 25]])

In [65]:
accuracy_score(y_test, knn_classification1.predict(x_test_scaled))

0.5392156862745098

# KNN with multiple neighbors

In [66]:
#  KNN with only one neighbor
knn_classification3 = KNeighborsClassifier(n_neighbors=3)

In [67]:
knn_classification3.fit(x_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [68]:
confusion_matrix(y_test, knn_classification3.predict(x_test_scaled))

array([[32, 26],
       [21, 23]])

In [69]:
accuracy_score(y_test, knn_classification3.predict(x_test_scaled))

0.5392156862745098

# Automatically running multiple neighbors in the KNN finding best among it

In [71]:
from sklearn.model_selection import GridSearchCV

In [89]:
# giving parameters as number of neighbors to test individually finding out best number of neighbor as per model
parameters = {'n_neighbors':[1,2,3,4,5,6,7,8,9,10,49]}

In [90]:
grid_search_cv = GridSearchCV(KNeighborsClassifier(),parameters)

In [91]:
grid_search_cv.fit(x_train_scaled, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 49]})

In [92]:
grid_search_cv.best_params_

{'n_neighbors': 9}

In [93]:
Optimized_KNN = grid_search_cv.best_estimator_

In [96]:
y_test_optimized_pred = Optimized_KNN.predict(x_test_scaled)

In [97]:
# directly use y_test_optimized_pred or use the function as below
confusion_matrix(y_test, Optimized_KNN.predict(x_test_scaled))

array([[36, 22],
       [18, 26]])

In [98]:
accuracy_score(y_test, Optimized_KNN.predict(x_test_scaled))

0.6078431372549019

#  notice how after changing the neighbors from 1 and 3 accuracy didnt get affected 
# but using optimized number of k gave us ≈ 7% more better and accurate results