In [1]:
# present working directory

In [46]:
pwd

'D:\\Dashboard\\miDirectarios\\ML\\start tech python\\ML Algorithms\\Logistic Regression'

In [47]:
import numpy as np
import seaborn as sns
import pandas as pd

In [48]:
df = pd.read_csv("D:\\Dashboard\\miDirectarios\\ML\\start tech python\\ML Algorithms\\Logistic Regression\\Classification preprocessed data Python.csv", header=0)

### already preprocessed data no need of imputation of missing valuse or other operations like dummy conversion 

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   price                     506 non-null    float64
 1   resid_area                506 non-null    float64
 2   air_qual                  506 non-null    float64
 3   room_num                  506 non-null    float64
 4   age                       506 non-null    float64
 5   teachers                  506 non-null    float64
 6   poor_prop                 506 non-null    float64
 7   n_hos_beds                506 non-null    float64
 8   n_hot_rooms               506 non-null    float64
 9   rainfall                  506 non-null    int64  
 10  parks                     506 non-null    float64
 11  Sold                      506 non-null    int64  
 12  avg_dist                  506 non-null    float64
 13  airport_YES               506 non-null    int64  
 14  waterbody_

In [51]:
"""
House Sales Prediction and Analysis

 Introduction
In this notebook, we aim to answer two key questions:
 1. **Prediction Question**: Will the house be sold within three
     months of being listed?
 2. **Inferential Question**: How accurately can we estimate the 
     response of the predictor variable on the response variable?
 
 We will use various machine learning techniques to address these questions.
 
 """

'\nHouse Sales Prediction and Analysis\n\n Introduction\nIn this notebook, we aim to answer two key questions:\n 1. **Prediction Question**: Will the house be sold within three\n     months of being listed?\n 2. **Inferential Question**: How accurately can we estimate the \n     response of the predictor variable on the response variable?\n \n We will use various machine learning techniques to address these questions.\n \n '

**Univariate Logistic Regression in Sci-kit lean**

In [52]:
# in sklearn our independant variablsem must be two dimensional so we use two brackets
x= df[['price']]

In [53]:
y=df['Sold']

In [54]:
x.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [55]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [56]:
from sklearn.linear_model import LogisticRegression
clf_lr = LogisticRegression()

In [57]:
clf_lr.fit(x,y)

LogisticRegression()

In [58]:
clf_lr.coef_ #beta 1

array([[-0.03571865]])

In [59]:
clf_lr.intercept_ #beta  0

array([0.61477516])

# using statsmodel for logistic regression

In [60]:
import statsmodels.api as sn

In [61]:
# by default statsmodels use 0 as constant so adding constant 
x_const = sn.add_constant(x)
x_const.head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [62]:
# importing logistic regression clasiffier
import statsmodels.discrete.discrete_model as Logmod

In [63]:
logit = Logmod.Logit(y,x_const).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [64]:
# detailed summary of model evaluation

# this is the advantage over sklearn
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Wed, 09 Oct 2024   Pseudo R-squ.:                 0.01788
Time:                        12:39:38   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

#this is showing that coef of price is - .03 which says thst 
#there is relation if zero was there there would be no relation
#the std error says the deviation of model from true value
# z= coef/std error

# the p> |z| value should be lower than threshold value threshold is given by ourselves

### only when the p value 8s less than threshold we set that gives relation others will make us unsure

In [75]:
clf_mlr = LogisticRegression()
clf_mlr.fit(x, y) 
clf_mlr.coef_


array([[-0.03571865]])

In [76]:
clf_mlr.intercept_

array([0.61477516])

### confusion matrix in python

In [79]:
clf_mlr.predict_proba(x)

array([[0.56032285, 0.43967715],
       [0.53910688, 0.46089312],
       [0.6512781 , 0.3487219 ],
       ...,
       [0.55944269, 0.44055731],
       [0.54265485, 0.45734515],
       [0.51596437, 0.48403563]])

In [81]:
y_predicted = clf_mlr.predict(x)
y_predicted

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [69]:
from sklearn.metrics import precision_score, recall_score

In [70]:
recall_score(y,y_predicted)

np.float64(0.2826086956521739)

In [71]:
from sklearn.metrics import roc_auc_score

In [72]:
roc_auc_score(y,y_predicted)

np.float64(0.5181159420289855)

In [83]:
y_pred_03 = (clf_mlr.predict_proba(x)[:,1]>=0.3).astype(bool)

In [84]:
from sklearn.metrics import confusion_matrix

In [86]:
# 30% threshold
confusion_matrix(y,y_pred_03)

array([[ 29, 247],
       [  2, 228]])